[project]
name = "backend"
version = "0.1.0"
description = "Cloud60 Group Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.39.3",
    "fastapi[standard]>=0.116.0",
    "werkzeug>=3.1.3",
    "python-multipart>=0.0.6",
    "bcrypt>=4.0.1",
]
